export const THREE_FOR_TWO = 'THREE_FOR_TWO';
export const TWO_FOR_ONE_POUND = 'TWO_FOR_ONE_POUND';
export const BASE_ON_WEIGHT = 'BASE_ON_WEIGHT';
export const BUY_ONE_GET_ONE_FREE = 'BUY_ONE_GET_ONE_FREE';
export const DISCOUNT_AFTER_THREE = 'DISCOUNT_AFTER_THREE';
